// Generated by https://quicktype.io

export interface Recipe {
  id:                string;
  tipo:              string;
  title:             string;
  //ingredientes:      [Ingredientes];
  ingrediente:       string;
  unidadMedida:      string;
  cantidad:          string;
  preparacion:       string;
  coccion:           string;
  tiempoCoccion:     number;
  grados:            string;
  tiempoElaboracion: number;
  tiempoTotal:       number;
  alt_image?:        string;
}


export interface Ingredientes{
  nombre:            string;
  unidadMedida:      string;
  cantidad?:         number;
}
